package compiler;
import codegen.ast.*;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 42;
  public static final int READLINE = 22;
  public static final int LEFTPARENTHESES = 54;
  public static final int doubleConstant = 65;
  public static final int LEFTSQUAREBRACKET = 58;
  public static final int DOUBLE = 6;
  public static final int NOTEQUAL = 33;
  public static final int SEMI = 51;
  public static final int GREATER = 36;
  public static final int PRIVATE = 29;
  public static final int CONTINUE = 31;
  public static final int INT = 5;
  public static final int intConstant = 62;
  public static final int ADDITIONASSIGNMENT = 47;
  public static final int MINUS = 45;
  public static final int LESS = 35;
  public static final int FOR = 12;
  public static final int stringConstant = 64;
  public static final int DEFINE = 2;
  public static final int RIGHTCURLYBRACKET = 57;
  public static final int NOT = 40;
  public static final int AND = 39;
  public static final int READINTEGER = 21;
  public static final int LESSEQUAL = 34;
  public static final int SUBTRACTIONASSIGNMENT = 48;
  public static final int OR = 41;
  public static final int COMMA = 52;
  public static final int BOOL = 7;
  public static final int CLASS = 9;
  public static final int EQUALEQUAL = 38;
  public static final int boolConstant = 63;
  public static final int NEWARRAY = 19;
  public static final int PLUS = 44;
  public static final int MULTIPLY = 43;
  public static final int IF = 14;
  public static final int LEFTRIGHTSQUAREBRACKET = 60;
  public static final int THIS = 11;
  public static final int ID = 61;
  public static final int DOT = 53;
  public static final int EOF = 0;
  public static final int RETURN = 16;
  public static final int EQUAL = 32;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int LINE = 28;
  public static final int MULTIPLICATIONASSIGNMENT = 49;
  public static final int NULL = 10;
  public static final int MOD = 46;
  public static final int BREAK = 17;
  public static final int VOID = 4;
  public static final int AUGMENTEDASSIGNMENT = 50;
  public static final int DTOI = 23;
  public static final int GREATEREQUAL = 37;
  public static final int IMPORT = 3;
  public static final int ELSE = 15;
  public static final int FUNC = 27;
  public static final int ITOD = 24;
  public static final int ITOB = 26;
  public static final int WHILE = 13;
  public static final int PUBLIC = 30;
  public static final int BTOI = 25;
  public static final int STRING = 8;
  public static final int DEFINESTMT = 66;
  public static final int RIGHTSQUAREBRACKET = 59;
  public static final int LEFTCURLYBRACKET = 56;
  public static final int RIGHTPARENTHESES = 55;
  public static final int PRINT = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEFINE",
  "IMPORT",
  "VOID",
  "INT",
  "DOUBLE",
  "BOOL",
  "STRING",
  "CLASS",
  "NULL",
  "THIS",
  "FOR",
  "WHILE",
  "IF",
  "ELSE",
  "RETURN",
  "BREAK",
  "NEW",
  "NEWARRAY",
  "PRINT",
  "READINTEGER",
  "READLINE",
  "DTOI",
  "ITOD",
  "BTOI",
  "ITOB",
  "FUNC",
  "LINE",
  "PRIVATE",
  "PUBLIC",
  "CONTINUE",
  "EQUAL",
  "NOTEQUAL",
  "LESSEQUAL",
  "LESS",
  "GREATER",
  "GREATEREQUAL",
  "EQUALEQUAL",
  "AND",
  "NOT",
  "OR",
  "DIVIDE",
  "MULTIPLY",
  "PLUS",
  "MINUS",
  "MOD",
  "ADDITIONASSIGNMENT",
  "SUBTRACTIONASSIGNMENT",
  "MULTIPLICATIONASSIGNMENT",
  "AUGMENTEDASSIGNMENT",
  "SEMI",
  "COMMA",
  "DOT",
  "LEFTPARENTHESES",
  "RIGHTPARENTHESES",
  "LEFTCURLYBRACKET",
  "RIGHTCURLYBRACKET",
  "LEFTSQUAREBRACKET",
  "RIGHTSQUAREBRACKET",
  "LEFTRIGHTSQUAREBRACKET",
  "ID",
  "intConstant",
  "boolConstant",
  "stringConstant",
  "doubleConstant",
  "DEFINESTMT"
  };
}

